// <auto-generated />
using Atividade_13._11___Sistema_Animais_MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Atividade_13._11___Sistema_Animais_MVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251113132624_CriarBanco")]
    partial class CriarBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Atividade_13._11___Sistema_Animais_MVC.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoAnimal")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("TabelaAnimal");

                    b.HasDiscriminator<string>("TipoAnimal").HasValue("Animal");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Atividade_13._11___Sistema_Animais_MVC.Models.Elefante", b =>
                {
                    b.HasBaseType("Atividade_13._11___Sistema_Animais_MVC.Models.Animal");

                    b.HasDiscriminator().HasValue("Elefante");
                });

            modelBuilder.Entity("Atividade_13._11___Sistema_Animais_MVC.Models.Leao", b =>
                {
                    b.HasBaseType("Atividade_13._11___Sistema_Animais_MVC.Models.Animal");

                    b.HasDiscriminator().HasValue("Leao");
                });
#pragma warning restore 612, 618
        }
    }
}
